# Generated by Django 4.2.20 on 2025-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_user_type_client_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'admin'), ('Client', 'client')], max_length=50),
        ),
    ]
