# Generated by Django 3.2.19 on 2024-04-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20240427_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='image',
            new_name='images',
        ),
    ]
