# Generated by Django 3.2.19 on 2024-04-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_image_message_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
