# Generated by Django 3.2.19 on 2024-04-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_message_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='images',
        ),
    ]
