# Generated by Django 3.2.19 on 2024-04-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_message_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
