# Generated by Django 3.2.19 on 2024-04-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
