# Generated by Django 3.2.19 on 2024-04-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
