# Generated by Django 3.2.19 on 2024-04-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20240428_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
