# Generated by Django 3.2.19 on 2024-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20240428_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
