# Generated by Django 3.2.19 on 2024-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_message_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
