# Generated by Django 3.2.19 on 2024-04-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_message_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
    ]
