# Generated by Django 3.2.19 on 2024-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_message_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
