# Generated by Django 3.2.19 on 2024-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20240430_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
