# Generated by Django 3.2.19 on 2024-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20240430_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
