# Generated by Django 3.2.19 on 2024-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='subject',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
