# Generated by Django 3.2.19 on 2024-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_report_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
