# Generated by Django 3.2.19 on 2024-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_report_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, max_length=52428800, upload_to=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, max_length=5242880, null=True, upload_to=''),
        ),
    ]
