# Generated by Django 3.2.19 on 2024-05-02 10:45

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20240502_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, max_length=52428800, upload_to='', validators=[base.models.file_size]),
        ),
    ]
