# Generated by Django 3.2.19 on 2024-05-02 19:19

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_message_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='files',
            field=models.FileField(blank=True, default=None, max_length=5248280000, upload_to='', validators=[base.models.file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
