# Generated by Django 3.2.19 on 2024-05-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20240502_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
